plugins {
    id 'com.android.application'
}

android {
    namespace 'com.finreg.knowledgebase'
    compileSdk 35

    defaultConfig {
        applicationId 'com.finreg.knowledgebase'
        minSdk 26
        targetSdk 35
        versionCode 12
        versionName '1.7.3'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    packaging {
        jniLibs.useLegacyPackaging = false
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
